[SERVICE]
    Flush        1
    Daemon       off
    Log_Level    info

[INPUT]
    Name             tail
    Tag              docker.*
    Path             /var/lib/docker/containers/*/*.log
    DB               /var/log/flb_docker.db
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    Parser           docker # Docker JSONログの解析

[OUTPUT]
    Name             es
    Match            *
    Host             elasticsearch-host
    Port             9200
    Index            java-app-%Y.%m.%d
    Type             _doc
    Suppress_Type_Name On