[SERVICE]
    Flush        1
    Daemon       off
    Log_Level    info
    Parsers_File fluent-bit-parsers.conf

[INPUT]
    Name             tail
    Tag              docker.*
    Path             /var/lib/docker/containers/*/*.log
    DB               /var/log/flb_docker.db
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    Parser           docker

[FILTER]
    Name             grep
    Match            *
    Exclude          tag cpu\.local

[FILTER]
    Name             parser
    Match            docker.*
    Key_Name         log
    Parser           spring-app-json
    Reserve_Data     On
    Preserve_Key     On

[OUTPUT]
    Name             es
    Match            docker.*
    Host             elasticsearch-host
    Port             9200
    Index            java-app-%Y.%m.%d
    Type             _doc
    Suppress_Type_Name On