version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  mailpit:
    image: axllent/mailpit:latest
    # http://localhost:8025
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    volumes:
      - ./mailpit:/data
    environment:
      TZ: Asia/Tokyo
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    deploy:
      resources:
        limits:
          cpus: '0.025'
          memory: 128M
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: your_dev_db         # 任意のデータベース名に変更
      POSTGRES_USER: your_user         # 任意のユーザー名に変更
      POSTGRES_PASSWORD: your_password # 任意のパスワードに変更
      TZ: Asia/Tokyo
    command: postgres -c 'timezone=Asia/Tokyo'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull llama3 && wait" ]
volumes:
  db_data:
  ollama_data:
