#--spring.profiles.active=dev
spring.application.name=restful
spring.datasource.url=jdbc:postgresql://localhost:5432/your_dev_db
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.enabled=true
system.mail.from=test@example.com
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
logging.level.jp.ne.yonem.restful.demo.mapper=DEBUG
