#--spring.profiles.active=dev
spring.application.name=restful
spring.datasource.url=jdbc:postgresql://localhost:5432/your_dev_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
api.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8083}
springdoc.swagger-ui.enabled=true
system.mail.from=${MAIL_FROM:test@example.com}
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.retries=0
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate
spring.servlet.multipart.max-file-size=100MB
encryption.password=${ENCRYPTION_PASSWORD}
jwt.publicKey=${JWT_PUBLIC_KEY}
jwt.privateKey=${JWT_PRIVATE_KEY}
jwt.expiration=${JWT_EXPIRATION:3600000}
batch.cron.expression=${BATCH_CRON_EXPRESSION:0/5 * * * * *}
