spring.application.name=restful
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.enabled=false
logging.level.root=INFO
encryption.password=${ENCRYPTION_PASSWORD}
jwt.publicKey=${JWT_PUBLIC_KEY}
jwt.privateKey=${JWT_PRIVATE_KEY}
jwt.expiration=${JWT_EXPIRATION:3600000}
