#--spring.profiles.active=prod
spring.application.name=restful
spring.datasource.url=jdbc:postgresql://localhost:5432/your_dev_db
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.enabled=false
logging.level.root=INFO
