#--spring.profiles.active=dev
spring.application.name=restful
spring.datasource.url=jdbc:postgresql://localhost:5432/your_dev_db
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
api.cors.allowed-origins=http://localhost:8083
springdoc.swagger-ui.enabled=true
system.mail.from=test@example.com
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.retries=0
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=your_keystore_password
#server.ssl.key-alias=your_key_alias
#server.ssl.key-password=your_keystore_password
encryption.password=your_32character_secret_key_here
jwt.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArYgGqqlI7moaw325PU6Urm0QoDtbT6oqQuDfE0NTjjQkLimdVdvGizqhPNOWFVnCACcjcu2rocgHBu7b/IGlAsEt2v+TTjQnG1ExgpCXzmFEVsYXIIMNHvIvHg3c4fA2+iJXNBHaX/CvJtkn5Vz12Ud+EH3roNG8iofyeo9Yqial48imOgXoQfMCwlkAJGbrHjHwRIN+GzdWnPNs7Qk2Eb4qUBvuy7pB1XZ8EFvfg4yjqodnurxouQ0DQucGMXoCroezjiQtJ/KmkCvPMw+EghqxexQGHq3AzAk56AD3FsIwDoLM353OoVt8A6QMOkqG7sQvnjLPLSolsuwnROD/awIDAQAB
jwt.privateKey=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtiAaqqUjuahrDfbk9TpSubRCgO1tPqipC4N8TQ1OONCQuKZ1V28aLOqE805YVWcIAJyNy7auhyAcG7tv8gaUCwS3a/5NONCcbUTGCkJfOYURWxhcggw0e8i8eDdzh8Db6Ilc0Edpf8K8m2SflXPXZR34Qfeug0byKh/J6j1iqJqXjyKY6BehB8wLCWQAkZuseMfBEg34bN1ac82ztCTYRvipQG+7LukHVdnwQW9+DjKOqh2e6vGi5DQNC5wYxegKuh7OOJC0n8qaQK88zD4SCGrF7FAYercDMCTnoAPcWwjAOgszfnc6hW3wDpAw6SobuxC+eMs8tKiWy7CdE4P9rAgMBAAECggEAHvrN1eHq90VSCdyEGYHR4WHvOeve3VYPvWjP6mx2mkiMvQEI6a8Wvvx0lJthi+Y+UDCsj3QG1BcVyhMSiv3KK7e5LAO8lJWS9bmFET4nG90ZijRLJK7AxOmPp9npuRxddEJ1NwKI7d/WJSVXjgcOjP/Kbb9NNaS7+C9VBrRYq+d2jVlvDB7h3CihF5sh4rKIwlmwvTGixVJyinBjaWclCpp62KIkZ/V6ndHi+Mi4XmeDeI0ufHuqlBW+QkjWJt40zLCVelZL+rmCtNPI80oGYrL2JbP9+JJpeJoNtHIAr7+ZCKuBv/VlPFJBh2fIrYAkn1qNGJnECuk7Dz4df+S2wQKBgQC5XMszL/kuPYonT6RzWAIM0DNX97LkxL1TqFD+q2JKCeSf4WaA7QXFRDjukShdCZ/3OiGl8DH5fFRxTx5xl5erU90GMvnnp6PqVl24OEyvuE/voXKADIxjKkDXb3sV3qmba1hlULvxhYVnjBs/FjUUB9uZy3NtdJ0XDqIH7seywwKBgQDvqQlBjkCVXeO1uKFDPYzKPi/jriyVr0i9cbnYjkPLWNFIMrwlRM0ce/Y0mrCNb4MU8CoWpoW6mTlZrOk3Zbas4v6mdy1It5algbFubwMJBc1dRgXq+Hpq9PA+ceCzwdkysfHmec7u1ofLnOCVXJrI8k3s1okxIblMxYWe5gXmOQKBgQCW1i38f2NT/3v2tVZrDgjNCHdfdA89HeO6udL/CdO30AkdGTxiWX5Colt5tuGTpAtqEQHkmGryS/wjIHDzmpovLtVDACRgIAjA3nrxN88fhup1Y3lbPdrXr0CIjw0oJML72ARcna/yv+Zo9pgNZDLZE/PdWLObNDPI2X182w/iJQKBgHXrYAiHa7OSrNXe8EnbYQiprHqEWp+TzWCZMm4hIa5OFztE61oTDjDztWKQskoFEiQdPzhB2w7DEXrUHzQIsedDETTq8rcSzebFd3301TN9TVyVdZf1hpZVylePRJZtzOaqs3FJgc32dH50w/P5ypcQ0dK0hHBOPZROo75ZQ5HRAoGAJNstpmZuwkATkQQsopSfowTdJchwwpj+/Hcgis7OZkb6EWx5U7srnVczpaH6vRV8dEaAaAl/FuMDfvMi6zBkT07Tr6EwVvoOV45ailtz7oJwIMxsMPVkghfu6KdidN7jgLOMHdM7WdPshBIrr6wTXwR7tTEANPyQt79cTvXSA8E=
jwt.expiration=3600000
logging.level.jp.ne.yonem.restful.demo.mapper=DEBUG
# cron式は「秒 分 時 日 月 曜日」の順で指定する
# アスタリスク(*)は「全て」を意味し、カンマ(,)はリスト、ハイフン(-)は範囲、スラッシュ(/)は間隔を示す
# 例: 0 0 0 * * コマンド は毎日午前0時0分にコマンドを実行する
batch.cron.expression=0/5 * * * * *
